import React,{useEffect,useState} from 'react';
import {AppState,Linking,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {DEFAULT_REMINDER} from './reminder-model.mjs';
import {googleCalendarUrl} from './calendar-reminder.mjs';
import {supported,readReminder,enableReminder,disableReminder,ReminderState} from './reminders';
export default function ReminderSettings(){
 const [state,setState]=useState<ReminderState|null>(null),[day,setDay]=useState(String(DEFAULT_REMINDER.day)),[hour,setHour]=useState(String(DEFAULT_REMINDER.hour)),[minute,setMinute]=useState('00'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function apply(value:ReminderState){setState(value);if(value.schedule){setDay(String(value.schedule.day));setHour(String(value.schedule.hour).padStart(2,'0'));setMinute(String(value.schedule.minute).padStart(2,'0'));}}
 useEffect(()=>{let active=true;const refresh=()=>readReminder().then(v=>{if(active)apply(v);}).catch(()=>{if(active)setError('Could not read reminder settings. Reopen this screen to retry.');});void refresh();const listener=AppState.addEventListener('change',v=>{if(v==='active')void refresh();});return()=>{active=false;listener.remove();};},[]);
 async function save(disable=false){setBusy(true);setError('');try{apply(disable?await disableReminder():await enableReminder({day:Number(day),hour:Number(hour),minute:Number(minute)}));}catch(e){setError(e instanceof Error?e.message:'Could not update your reminder. Please try again.');}finally{setBusy(false);}}
 function openCalendar(){setError('');try{const url=googleCalendarUrl({day:Number(day),hour:Number(hour),minute:Number(minute)});window.location.assign(url);}catch(e){setError(e instanceof Error?e.message:'Could not open your calendar.');}}
 const disabled=busy||(supported&&!state);
 return <View style={s.card}><Text style={s.title}>{supported?'Monthly reminder':'Monthly calendar reminder'}</Text><Text style={s.body}>{supported?'A gentle nudge to complete your survey. Choose a day and local time; reminders repeat each month until you turn them off.':'Choose a day and local time, then open Google Calendar. Check the event’s notification time and press Save there to set the monthly reminder.'}</Text>
 {!supported?<Text style={s.notice}>Google Calendar stores this event in your account and controls its alerts. The event includes the tracker link, but no answers or scores.</Text>:<Text accessibilityLiveRegion="polite" style={s.notice}>{!state?'Loading…':state.schedule?(state.allowed?'Reminder is scheduled.':'Scheduled, but notifications are blocked in device settings.'):'Reminders are off.'}</Text>}
 <View style={s.row}>{[{label:'Day (1–28)',value:day,set:setDay},{label:'Hour (0–23)',value:hour,set:setHour},{label:'Minute (0–59)',value:minute,set:setMinute}].map(f=><View key={f.label} style={s.field}><Text style={s.label}>{f.label}</Text><TextInput accessibilityLabel={f.label} editable={!disabled} keyboardType="number-pad" maxLength={2} value={f.value} onChangeText={v=>f.set(v.replace(/[^0-9]/g,''))} style={s.input}/></View>)}</View>
 <Text style={s.small}>Days 1–28 are available so your reminder occurs every month. The survey still asks about the previous month.</Text>
 {!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
 <Pressable accessibilityRole="button" disabled={disabled||!day||!hour||!minute} onPress={supported?()=>void save():openCalendar} style={[s.button,(disabled||!day||!hour||!minute)&&s.disabled]}><Text style={s.buttonText}>{supported?(busy?'Updating…':state?.schedule?'Save reminder changes':'Enable monthly reminder'):'Set in Google Calendar →'}</Text></Pressable>
 {supported&&state?.schedule&&<Pressable accessibilityRole="button" disabled={disabled} onPress={()=>void save(true)} style={s.secondary}><Text style={s.link}>Turn off reminder</Text></Pressable>}
 {supported&&state&&!state.allowed&&<Pressable accessibilityRole="button" onPress={()=>void Linking.openSettings().catch(()=>setError('Open your device Settings app to manage notification permissions.'))}><Text style={s.link}>Open device settings</Text></Pressable>}
 {supported&&state?.schedule&&state.allowed&&state.next&&<Text style={s.small}>Next reminder: {new Date(state.next).toLocaleString()}</Text>}
 <Text style={s.small}>{supported?'Notification text contains no scores or answers. Delivery may be delayed by battery saving or Focus settings. Completing a survey does not change your chosen schedule.':'Choosing a time here does not save an event by itself. To change or turn off a saved reminder, edit it in Google Calendar.'}</Text></View>;
}
const s=StyleSheet.create({card:{backgroundColor:'white',borderRadius:20,borderWidth:1,borderColor:'#E4E9DF',padding:20,gap:16},title:{fontSize:20,fontWeight:'600',color:'#203D36'},body:{fontSize:14,lineHeight:22,color:'#637368'},notice:{fontSize:14,lineHeight:22,color:'#24665D'},row:{flexDirection:'row',gap:10},field:{flex:1,gap:8},label:{fontSize:11,color:'#637368'},input:{borderWidth:1,borderColor:'#CCD9C8',borderRadius:12,padding:12,fontSize:18,color:'#203D36'},small:{fontSize:12,lineHeight:19,color:'#738175'},button:{backgroundColor:'#24665D',padding:16,borderRadius:14,alignItems:'center'},buttonText:{color:'white',fontWeight:'600'},disabled:{opacity:.45},secondary:{padding:12,alignItems:'center'},link:{color:'#24665D',fontSize:14},error:{color:'#A03D28',fontSize:14,lineHeight:22}});
